nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Tenant-Context', 'X-Hospital-ID']
        expose_headers: ['Link', 'X-Total-Count', 'X-Tenant-Name']
        max_age: 3600
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'X-Tenant-Context', 'X-Hospital-ID']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
