security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Member:
            algorithm: auto
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_member_provider:
            id: App\Security\MemberProvider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_member_provider
            
            # Formulario de login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_dashboard_default
            
            # Remember me cookie
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semana en segundos
                path: /
                always_remember_me: false
            
            # Logout
            logout:
                path: app_logout
                target: app_login
            
            # Autenticador personalizado
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

    # Control de acceso
    # Note: Solo el *primer* access control que coincida será usado
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/tenants, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # En tests, reducir el costo para mejorar performance
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valor mínimo para bcrypt
                time_cost: 3 # Valor mínimo para argon
                memory_cost: 10 # Valor mínimo para argon
