#_Caja_Supervisor_UbicacionCaja:
#    path:  /
#    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCaja:index }

Caja_Supervisor_UbicacionCaja:
    path:  /listado
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCaja:index }

Caja_Supervisor_UbicacionCaja_show:
    path:  /{id}/ver
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCajaVer:ver }

Caja_Supervisor_UbicacionCaja_new:
    path:  /nuevo
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCajaNuevo:nuevo }

Caja_Supervisor_UbicacionCaja_create:
    path:  /crear
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCajaNuevo:crear }

Caja_Supervisor_UbicacionCaja_edit:
    path:  /{id}/editar
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCajaEditar:editar }

Caja_Supervisor_UbicacionCaja_update:
    path:  /{id}/actualizar
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCajaEditar:actualizar }

Caja_Supervisor_UbicacionCaja_delete:
    path:  /{id}/eliminar
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/UbicacionCaja/UbicacionCajaEliminar:eliminar }