#_Caja_Supervisor_AutorizacionDescuentos:
#    path:  /
#    defaults: { _controller: RecaudacionBundle:Supervisor/AutorizacionDescuentos/AutorizacionDescuentos:index }

Caja_Supervisor_AutorizacionDescuentos:
    path:  /index
    defaults: { _controller: RecaudacionBundle:_Default/Supervisor/AutorizacionDescuentos/AutorizacionDescuentos:index }

Caja_Supervisor_AutorizacionDescuentosAprueba:
    path:  /aprueba/{idDiferencia}
    defaults: { _controller: RecaudacionBundle:_Default/Supervisor/AutorizacionDescuentos/AutorizacionDescuentosAprueba:aprueba }

Caja_Supervisor_AutorizacionDescuentosRechaza:
    path:  /rechaza/{idDiferencia}
    defaults: { _controller: RecaudacionBundle:_Default/Supervisor/AutorizacionDescuentos/AutorizacionDescuentosRechaza:rechaza }

Caja_Supervisor_AutorizacionDescuentosVer:
    path:  /ver/{idDiferencia}
    defaults: { _controller: RecaudacionBundle:_Default/Supervisor/AutorizacionDescuentos/AutorizacionDescuentosVer:ver }
