Caja_PagoCuenta_CasePayApi:
    path:  /CasePayApi
    defaults: { _controller: CajaBundle:Api/Unab/PagoCuenta/Pago/Pagar:cajaPagarApi}

Caja_PagoCuenta_CasePay:
    path:  /CasePay
    defaults: { _controller: CajaBundle:Api/Unab/PagoCuenta/Pago/Pagar:cajaPagar}

Caja_PagoCuenta_CasePayMediosPago:
    path:  /CasePayMediosPagos
    defaults: { _controller: CajaBundle:Api/Unab/PagoCuenta/Pago/Pagar:cajaPagarMediosPago}

Caja_PagoCuenta_PeopleId:
    path:  /PeopleId
    defaults: { _controller: CajaBundle:Api/Unab/PagoCuenta/Pago/Pagar:persona}
