global:
  name: settings.global.name
  description: settings.global.description
  available_in_frontend: 1
  children:
    general:
      name: General
      description: NULL
      available_in_frontend: 1
      folio: 3.7
      children:
        instance_language:
          name: Language
          description: NULL
          field_format: choice
          field_available_value:
            es: Español
            en: Inglés
          field_default_value: es_CL
          available_in_frontend: 1
          available_in_wizard: 1
          folio: 3.7.4
        enable_instance:
          name: Enable instance
          description: NULL
          field_format: boolean
          field_available_value: NULL
          field_default_value: 1
          available_in_frontend: 1
          folio: 3.7.5
        contracted_licenses:
          name: Contracted licenses
          description: NULL
          field_format: integer
          field_available_value: NULL
          field_default_value: 50
          available_in_frontend: 1
          available_in_wizard: 1
          folio: 3.7.6
    dashboard:
      name: Dashboard
      description: NULL
      available_in_frontend: 1
      folio: 3.6
      children:
        dashboard_widgets:
          name: Habilitar widgets en Dashboard
          description: NULL
          field_format: boolean
          field_default_value: NULL
          available_in_frontend: 1
          folio: 3.6.1
outpatient:
  name: settings.outpatient.name
  description: settings.outpatient.description
  available_in_frontend: 1
  children:
    outpatient_resources:
      name: Outpatient Resources
      description: NULL
      available_in_frontend: 1
      folio: 1.19
      children:
        outpatient_anamnesis:
          name: Habilitar modulo de Anamnesis
          description: NULL
          field_format: boolean
          field_available_value: NULL
          field_default_value: 0
          available_in_frontend: 1
          folio: 1.19.1
        outpatient_diagnostic:
          name: Habilitar modulo de Diagnosticos
          description: NULL
          field_format: boolean
          field_available_value: NULL
          field_default_value: 0
          available_in_frontend: 1
          folio: 1.19.2
hospital:
  name: settings.hospital.name
  description: settings.hospital.description
  available_in_frontend: 1
  children:
    hospital_resources:
      name: Hospital Resources
      description: NULL
      available_in_frontend: 1
      folio: 1.18
      children:
        hospital_anamnesis:
          name: Habilitar modulo de Anamnesis
          description: NULL
          field_format: boolean
          field_available_value: NULL
          field_default_value: 0
          available_in_frontend: 1
          folio: 1.18.1
        hospital_diagnostic:
          name: Habilitar modulo de Diagnosticos
          description: NULL
          field_format: boolean
          field_available_value: NULL
          field_default_value: 0
          available_in_frontend: 1
          folio: 1.18.2