Caja_Supervisor_ReporteProduccion:
    path:  /
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/ReporteProduccion/ReporteProduccion:index }

Caja_Supervisor_ReporteProduccion_Descargas:
    path:  /Descarga/{fechaIni}/{fechaFin}
    defaults: { _controller: App\Controller\Caja\_Default/Supervisor/ReporteProduccion/Descarga:excel }
