recaudacion_recaudacion:
    path:  /Recaudacion
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Default:index }

Caja_Recaudacion_Pago_ValRut:
    path:  /BusquedaRut
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Dependencias\Valrut:indexRut }

Caja_Recaudacion_Pago_ValExtranjeros:
    path:  /BusquedaExtranjero
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Dependencias\Valrut:indexExtranjero }

Caja_Recaudacion_Pago_ObtieneDomicilio:
    path:  /ObtieneDomicilio
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Dependencias\Avanzada:domicilio  }

Caja_Recaudacion_Pago_ObtieneDatosNUsuarios:
    path:  /ObtieneDatosNUsuarios
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Dependencias\Avanzada:obtieneDatosNUsuarios  }

Caja_Recaudacion_Pago_ObtieneDatosUnUsuario:
    path:  /ObtieneDatosUnUsuario
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Dependencias\Avanzada:obtieneDatosUnUsuario  }

Caja_Recaudacion_Pago_Avanzada:
    path:  /BusquedaAvanzada
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Dependencias\Avanzada:indexAdv }

Caja_ActualizaPaciente:
    path:  /actualizaPaciente
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:actualizaPaciente }

Caja_CreaPaciente:
    path:  /creaPaciente
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:creaPaciente }

Caja_ConsultaPacienteIdPnatural:
    path:  /consultaIpPnatural
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:consultaPaciente }

Caja_Consulta_Planes:
    path:  /consulaPlanes
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:consulaPlanes }

Caja_Consulta_Profesionales:
    path:  /consulaProfesionales
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:consulaProfesionales }

#Caja_Consulta_Externos:
#    path:  /consulaExternos
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:busquedaExterno }

#Caja_Obtiene_Externo:
#    path:  /ObtieneExterno
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:obtieneExterno }

Caja_Consulta_Origen:
    path:  /consulaOrigen
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:consulaOrigen }

Caja_Recaudacion_vresultadoBusquedaAvanzadaPaciente:
    path:  /PagoBusquedaAvanzadaPacientes
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Pago/Dependencias/Avanzada:resultadoBusquedaAvanzadaPaciente }


Caja_getNuevoFormDinamico:
    path:  /Caja_getNuevoFormDinamico
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:nuevoFormDinamico}

#VALIDA SI YA SE HA OCUPADO UN BONO DE ACUERDO A SU CLASIFICACION
Caja_Valida_Bono:
    path:  /CajaValidaBono
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:validaBono}

#VALIDA VALORES POR PAGAR
Caja_Valor_Pagar:
    path:  /CajaValorPagar
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:cajaValorPagar}
    
Caja_Valor_Pagar_Pago_Cuenta:
    path:  /CajaValorPagarPagoCuenta
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:cajaValorPagarPagoCuenta}

#VALIDA VALORES POR PAGAR
Caja_Valmacena_Total_Suma:
    path:  /CajaValmacenaTotalSuma
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:cajaValmacenaTotalSuma}

#VALIDA VALORES POR PAGAR
Caja_Valor_Pagar_Comparar_Tabs:
    path:  /CajaValorPagarCompararTabs
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:cajaValorPagarCompararTabs}

#VALIDA VALORES POR PAGAR
#Caja_CMPVP:
#    path:  /CMPVP
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\MedioPago:CMPVP}

Caja_CasePayApi:
    path:  /CasePayApi
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pagar:cajaPagarApi}

Caja_CasePay:
    path:  /CasePay
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pagar:setSessionCajaPagar }

Caja_CasePayMediosPago:
    path:  /CasePayMediosPago
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pagar:cajaPagarMediosPago}

Caja_PeopleId:
    path:  /PeopleId
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pagar:persona}

#Caja_PostPago:
#    path:  /PostPago
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:index }

Caja_PostPago_PrintDetallePago:
    path:  /DetallePago/{id}
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:detallesPago }
    requirements: { id: \d+ }

Caja_PostPago_PrintDetalleAtencion:
    path:  /{id}/DetalleAtencion
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:detallesAtencion }
    requirements: { id: \d+ }

Caja_PostPago_PrintDetalleBoleta:
    path:  /{id}/DetalleBoleta
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:detallesBoleta }
    requirements: { id: \d+ }

Caja_PostPago_Historial:
    path:  /PostPagoHistorial
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:historialPaciente }

Caja_PostPago_PrintDetalleAtencion_ImpresionPDF:
    path:  /DetalleAtencionPrinter
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:imprimirDetalleAtencion }

Caja_PostPago_PrintDetallePago_ImpresionPDF:
    path:  /DetallePagoPrinter
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:imprimirDetallePago }
    methods: [POST]

Caja_PostPago_PrintDetalleBoleta_ImpresionPDF:
    path:  /DetalleBoletaPrinter
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:imprimirDetalleBoleta }
    methods: [POST]

Caja_PostPago_ReenviarDte:
    path:  /ReenviarDte
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:reenviarDte }

Caja_PostPago_PrintDetallesCaja_ImpresionPDF:
    path:  /DetallesCajaPrinter
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/GestionCaja/GestionCaja:gestionInformeCajaImprimir }
    methods: [POST]

Caja_PostPago_Boleta:
    path:  /postPagoBoleta
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:postPagoBoleta }

Caja_Boleta_ModificaNumero:
    path:  /ModificaBoleta
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:modificaBoleta }

#Caja_Boleta_ModificaNumero_Manual:
#    path:  /ModificaBoletaManual
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:modificaBoletaManual }

Caja_PostPago_AnulacionPagoAgenda:
    path:   /AnulacionPagoAgenda
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:anulacionPagoAgenda }


#Caja_PostPago_AnulacionPagoAgenda_Api1:
#    path:   /AnulacionPagoAgendaApi1
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:anulacionPagoAgendaApi1 }

Caja_PostPago_AnulacionPagoCaja:
    path:  /{id}/AnulacionPagoCaja
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:anulacionPagoCaja }
    requirements: { id: \d+ }

Caja_PagoCuenta_AnulacionPagoCaja:
    path:  /{id}/AnulacionPagoCajaPagoCuenta
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:anulacionPagoCajaPagoCuenta }
    requirements: { id: \d+ }

Caja_PostPago_PagoGarantia:
    path:  /PagoGarantia
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoGarantia }

Caja_PostPago_PagoReserva:
    path:  /PagoReserva
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoReserva }

Caja_PostPago_DocumentosPostPago:
    path:  /DocumentosPostPago
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:documentosPostPago }

Caja_PostPago_Boleta_Dte:
    path:  /postPagoBoletaDte
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:postPagoBoletaDte }
    
Caja_PostPago_Regularizar_Garantia:
    path:  /postRegularizarGarantia
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:regularizaGarantia }


# GESTION CAJA
Caja_Gestion_CerrarCaja:
    path:  /{id}/GestionCerrarCaja
    defaults: { _controller:  RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionCerrarCaja }
    requirements: { id: \d+ }

Caja_Gestion_CerrarCajaCerrado:
    path:   /{id}/GestionCerrarCajaCerrado
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionCerrarCajaCerrado }
    requirements: { id: \d+ }

Caja_Gestion_AbrirCaja:
    path:  /GestionAbrirCaja
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionAbrirCaja}

Caja_Gestion_InformesCajas:
    path:   /{id}/InformeCajas
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionInformeCajas}
    requirements: { id: \d+ }

Caja_Gestion_InformeCaja:
    path:   /{id}/InformeCaja
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionInformeCaja}
    requirements: { id: \d+ }

Caja_Gestion_InformesGarantias:
    path:   /InformeGarantias
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionInformeGrantias}

Caja_TraeCorrelativo:
    path:  /TraeCorrelativo
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:traeCorrelativo}

Caja_Gestion_verificaCorrelativo:
    path:   /verificaCorrelativo
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:verificaCorrelativo }

Caja_GuardaFechaEnBaseDocumento:
    path:   /GuardaFechaEnBaseDocumento
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:guardaFechaEnBaseDocumento }

#Caja_Diferencia:
#    path:  /Diferencia
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:diferencia }


#Caja_Diferencia_ConsultaMotivoPorTipo:
#    path:  /DiferenciaConsultaMotivoPorTipo
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:consultaMotivoPorTipo }

#Caja_buscaPrestacionSubEmpresaDesdeAgenda:
#    path:  /buscaPrestacionSubEmpresaDesdeAgenda
#    defaults: { _controller: CajaBundle:_Default/Servicios/BuscarPrestaciones:buscaPrestacionSubEmpresaDesdeAgenda }

# GARANTIA
Caja_PostPago_PagoGarantia_BuscarPrestaciones:
    path:   /PagoGarantiaBuscarPrestaciones
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoGarantiaBuscarPrestaciones }

Caja_PostPago_PagoGarantia_BuscarHonorario:
    path:   /PagoGarantiaBuscarHonorario
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoGarantiaBuscarHonorario }

Caja_PostPago_PagoGarantia_BuscarArticulos:
    path:   /PagoGarantiaBuscarArticulos
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoGarantiaBuscarArticulos }

Caja_PostPago_PagoGarantia_VerificaSubEmpresaActualCajero_PrestacionesInsumos:
    path:   /VerificaSubEmpresaActualCajero_PrestacionesInsumos
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:reservaVerificaSubEmpresaActualCajeroPrestacionesInsumos }

Caja_PostPago_PagoGarantia_BuscaOtrosMedios:
    path:   /BuscaOtrosMedios
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoGarantiaBuscaOtrosMedios }

# RESERVA
Caja_PostPago_PagoReserva_VerificaSubEmpresaActualCajero_PrestacionesInsumos:
    path:   /ReservaVerificaSubEmpresaActualCajeroPrestacionesInsumos
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:reservaVerificaSubEmpresaActualCajeroPrestacionesInsumos }

Caja_PostPago_PagoReserva_BuscarPrestaciones:
    path:   /PagoReservaBuscarPrestaciones
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:pagoReservaBuscarPrestaciones }

# I-MED
Caja_Imed_Index:
    path:   /CajaImedIndex
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Imed/Imed:index }

Caja_Imed_Post_Trans_Auditoria:
    path:   /PostTransAuditoria
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Imed/Imed:sendPostLogin }

#@todo revisar este routing - function  verificaTalonarioPrestacion not exits in  Recaudacioncontroller
#Caja_Imed_VerificaTalonarioPrestacion:
#    path:   /VerificaTalonarioPrestacion
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/Imed/Imed:verificaTalonarioPrestacion }

#Caja_Imed_Post_Trans_Auditoria:
#    path:   /PostTransAuditoria
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/Imed/Imed:sendPostLogin }

# Caja_Imed_Post_Trans_Auditoria_Prueba:
#     path:   /PostTransAuditoriaPrueba
#     defaults: { _controller: RebsolHermesBundle:Pruebas\Pruebas:Index }

#Caja_Imed_SendGetObtBonInterfaz:
#    path:   /SendGetObtBonInterfaz
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/Imed/Imed:sendGetObtBonInterfaz }

# API
Caja_ActualizaPaciente_Api1:
    path:  /actualizaPacienteMascota
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:actualizaPacienteApi1 }

Caja_CreaPacienteApi:
    path:  /creaPacienteMascota
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:CreaPacienteApi }

Caja_Recaudacion_ConsultaMascotas:
    path:  /BuscaMascotasPorDueno
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:buscaMascotasPorDueno }

#Caja_Guarda_IdPnaturalMascota:
#    path:   /GuardaIdPnaturalMascota
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:guardaIdPnaturalMascota }

#Caja_BuscaMascotas_Cliente:
#    path:   /BuscaMascotasCliente
#    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:buscaMascotasCliente }

# TRATAMIENTO
Caja_Tratamiento_Crear:
    path:   /Crear_tratamiento
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Tratamiento/Tratamiento:crearTratamiento }

Caja_Tratamiento_Editar:
    path:   /EditarTratamiento
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Tratamiento/Tratamiento:editarTratamiento }

#Caja_Tratamiento_Crear_BuscarTratamiento_Pnatural:
#    path:   /CrearBucarTratamientoPnatural
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/Tratamiento/Tratamiento:crearTratamientoBuscarPnatural }

Caja_Tratamiento_Anulacion:
    path:   /{id}/Anular_tratamiento
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Tratamiento/Tratamiento:anularTratamiento }
    requirements: { id: \d+ }

Caja_Tratamiento_Glosa:
    path:  /Glosa_Tratamiento
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Tratamiento/Tratamiento:glosaTratamiento }

Caja_Tratamiento_Get_Edit:
    path:  /GetEdit_Tratamiento
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Tratamiento/Tratamiento:getEditartratamiento }

# DIFERENCIA
Caja_Diferencia_Generar:
    path:   /GenerarDiferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:generarDiferencia }

Caja_DiferenciaSaldo_Generar:
    path:   /GenerarDiferenciaSaldo
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:generarDiferenciaSaldo }

Caja_Diferencia_GetMotivosDiferencia:
    path:   /GetMotivosDiferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:getMotivosDiferencia }

Caja_Diferencia_GetTipoSentido:
    path:   /GetTipoSentido
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:getTipoSentido }

Caja_Diferencia_SendCountPrestacionArticulo:
    path:   /SendCountPrestacionArticulo
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:countPrestacionesArticulos }

Caja_Diferencia_SOlicitar:
    path:   /Solicitar_diferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:solicitarDiferencia }

Caja_Diferencia_SOlicitar_Saldo:
    path:   /Solicitar_diferencia_saldo
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:solicitarDiferenciaSaldo }

Caja_Diferencia_Anular:
    path:   /Anular_diferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:anularDiferencia }

Caja_Diferencia_Respuesta_SUpervisor:
    path:   /Respuesta_SUpervisor_diferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:respuestaSupervisorDiferencia }

Caja_ActualizaPacienteSinRut:
    path:  /ActualizaPacienteSinRut
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\Pago:actualizaPacienteSinRut }

Caja_Valida_Prevision_EsImed:
    path:   /CajaImedValidaPrevisionEsImed
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Imed/Imed:cajaImedValidaPrevisionEsImed }

Caja_Pregunta_Pago_esImed:
    path:   /CajaAnulaPagoEsImed
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Imed\Imed:cajaAnulaPagoEsImed }

############## SUBIR / ABRIR / ELIMINAR PDF ########
Caja_PostPago_SubirPDF:
    path:   /CajaPostPagoSubirPDF
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:subirPDF }
    methods: [POST]

Caja_PostPago_AbrirPDF:
    path:   /CajaPostPagoAbrirPDF
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:abrirPDF }

Caja_PostPago_EliminarPDF:
    path:   /CajaPostPagoEliminarPDF
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\Pago\PostPago:eliminarPDF }
    methods: [POST]


# RECAUDACION DESDE AGENDAMIENTO
#Caja_Caja_Recaudacion_Agendamiento:
#    path:  /{id}/Recaudacion
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/Recaudacion:indexPago }
#    requirements: { id: \d+ }

Caja_Diferencia_Aplicar:
    path:   /Aplicar_diferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:aplicarDiferencia }
    methods: [POST]

#Caja_Diferencia_Generar:
#    path:   /GenerarDiferencia
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/Diferencia:generarDiferencia }

###### VERIFICAR QUE EXISTE USUARIO INTEGRACIÃ“N
Caja_ExisteUsuarioIntegracion:
    path:  /consultaExisteUsuarioIntegracion
    defaults: { _controller: RecaudacionBundle:ApiPV/Recaudacion/Recaudacion:existeUsuarioIntegracion }

# pagos web
Caja_Gestion_InformeCajaPagosWeb:
    path:   /InformeCajaPagosWeb
    defaults: { _controller: RecaudacionBundle:_Default\Recaudacion\GestionCaja\GestionCaja:gestionInformeCajaPagosWeb}

#Caja_Gestion_InformePDFCajaPagosWeb:
#    path:   /InformeCajaPDFPagosWeb
#    defaults: { _controller: CajaBundle:_Default/Recaudacion/GestionCaja/GestionCaja:gestionInformeCajaPagosWebImprimir}

Caja_Diferencia_GetTipoSentidoPorMotivoDiferencia:
    path:   /GetTipoSentidoPorMotivoDiferencia
    defaults: { _controller: RecaudacionBundle:_Default/Recaudacion/Diferencia/Diferencia:getTipoSentidoPorMotivoDiferencia }
